name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  OUTDIR: _site

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        repo:
          - "benniekiss/minijinja-lua"
          - "benniekiss/rsre-lua"
          - "benniekiss/rsjson-lua"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: luarocks/gh-actions-lua@989f8e6ffba55ce1817e236478c98558e598776c # v11
        with:
          luaVersion: "5.1"

      - uses: luarocks/gh-actions-luarocks@7c85eeff60655651b444126f2a78be784e836a0a # v6

      - name: Download release assets
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1
        with:
          repository: ${{ matrix.repo }}
          latest: true
          fileName: "*.rock"

      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "chore: update rocks"
          file_pattern: "*.rock manifest*"

      - name: Prep site
        run: |
          mkdir -p ${{ env.OUTDIR }}
          mv index.html ${{ env.OUTDIR }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ${{ env.OUTDIR }}

  deploy:
    needs: upload
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
