name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-24.04, target: x86_64-unknown-linux-gnu }
          # - { os: ubuntu-24.04-arm, target: aarch64-unknown-linux-gnu }
          # - { os: macos-14, target: aarch64-apple-darwin }
          # - { os: windows-2025, target: x86_64-pc-windows-msvc }
        repo:
          - "benniekiss/minijinja-lua"

    steps:
      - uses: luarocks/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - uses: luarocks/gh-actions-luarocks@v6

      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ matrix.repo }}
          latest: true
          fileName: "*.rock"

      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update rocks"
          file_pattern: "*.rock manifest* index.html"
