name: Publish

on:
  workflow_dispatch:

env:
  SITE_DIR: "_site"

jobs:
  lua-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - id: version
        run: |
          echo "version=$(cat .lua-version)" >> "$GITHUB_OUTPUT"

  download-rock:
    name: download-rock ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    needs: lua-version

    strategy:
      fail-fast: false
      matrix:
        package:
          - { repo: "benniekiss/rs-mod-lua", tag: "minijinja-lua-v0.2.1", name: "minijinja-lua" }
          - { repo: "benniekiss/rs-mod-lua", tag: "rsjson-lua-v0.4.1", name: "rsjson-lua" }
          - { repo: "benniekiss/rs-mod-lua", tag: "rsre-lua-v0.3.1", name: "rsre-lua" }

    env:
      LUA_VERSION: ${{needs.lua-version.outputs.version}}

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1
        with:
          repository: ${{ matrix.package.repo }}
          tag: ${{ matrix.package.tag }}
          fileName: "${{ matrix.package.name }}*.rock"
          tarBall: false
          zipBall: false

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          if-no-files-found: "error"
          name: ${{ matrix.package.name }}
          path: |
            *.rock

  build-rock:
    name: build-rock ${{ matrix.package.name }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    needs: lua-version

    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-24.04, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-24.04-arm, target: aarch64-unknown-linux-gnu }
          - { os: macos-14, target: aarch64-apple-darwin }
          - { os: windows-2025, target: x86_64-pc-windows-msvc }
        package:
          - { name: "lux-lua" }

    env:
      LUA_VERSION: ${{needs.lua-version.outputs.version}}

    steps:
      - name: Setup Lux
        uses: lumen-oss/gh-actions-lux@d12a6bdf3a380de5b9d142272e6fd95d28b44b8d # v1
        with:
          version: ${{ vars.LUX_VERSION }}

      - name: Pack rock (windows)
        if: ${{ endsWith(matrix.job.target, '-msvc') }}
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lx --lua-version ${{ env.LUA_VERSION }} pack ${{ matrix.package.name }}

      - name: Pack rock (unix)
        if: ${{ !endsWith(matrix.job.target, '-msvc') }}
        run: |
          lx --lua-version ${{ env.LUA_VERSION }} pack ${{ matrix.package.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          if-no-files-found: "error"
          name: ${{ matrix.package.name }}-${{ matrix.job.target }}
          path: |
            *.rock

  upload:
    needs: [lua-version, download-rock, build-rock]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      LUA_VERSION: ${{needs.lua-version.outputs.version}}

    steps:
      - uses: luarocks/gh-actions-lua@989f8e6ffba55ce1817e236478c98558e598776c # v11
        with:
          luaVersion: ${{ env.LUA_VERSION }}

      - uses: luarocks/gh-actions-luarocks@7c85eeff60655651b444126f2a78be784e836a0a # v6

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          merge-multiple: true

      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=${{ env.LUA_VERSION }} .

      - name: Prep site
        run: |
          mkdir -p ${{ env.SITE_DIR }}
          mv *.rock manifest* index.html ${{ env.SITE_DIR }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    needs: upload
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
